set number
set cursorline
set hidden
set ignorecase
set smartcase
set expandtab
set tabstop=2
set shiftwidth=2
set iskeyword+=-
set backupdir^=~/.vim/_backup//
set directory^=~/.vim/_temp//
set t_ut=
set t_ti= t_te=
set colorcolumn=100
set background=dark
let base16colorspace=256
colorscheme base16-default-dark

" Auto reload files
autocmd CursorHold * checktime

" Disable cursorline on insert mode
autocmd InsertEnter,InsertLeave * set cursorline!

" Syntax highlight some oddly named files
autocmd BufNewFile,BufRead Vagrantfile set filetype=ruby
autocmd BufNewFile,BufRead *.gradle set filetype=groovy

" http://vimcasts.org/episodes/tidying-whitespace/
function! <SID>StripTrailingWhitespaces()
  let _s=@/
  let l = line(".")
  let c = col(".")
  %s/\s\+$//e
  let @/=_s
  call cursor(l, c)
endfunction

let mapleader = ","
nmap <C-n> :NERDTreeToggle<CR>
nnoremap <silent> <F5> :call <SID>StripTrailingWhitespaces()<CR>
nnoremap <C-t> :tabnew<CR>
inoremap <C-t> <Esc>:tabnew<CR>
nmap <C-k> :bnext<CR>
nmap <C-j> :bprev<CR>
" TODO: fix in linux or remove
map <leader>y "+y
nmap <leader>f :NERDTreeFind <CR>
" Save and run last command
nnoremap <leader>w :w<CR>:!clear; !<CR>

" Pasting code.
" http://vim.wikia.com/wiki/Toggle_auto-indenting_for_code_paste
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>

" Reindent the whole file
" http://vim.wikia.com/wiki/Fix_indentation
nmap <F7> mzgg=G`z<CR>

" Display wrapped text nicely.
" http://vimcasts.org/episodes/soft-wrapping-text/
set nowrap nolinebreak list
nnoremap <F4> :set wrap! linebreak! nolist! wrap?<CR>
imap <F4> <C-o><F4>

" Plugins config
cnoreabbrev rg Ack
cnoreabbrev Rg Ack
let g:ackprg = 'rg --vimgrep --smart-case'
let g:NERDTreeQuitOnOpen = 1
let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_html_checkers = []
let g:syntastic_javascript_checkers = []
" let g:syntastic_javascript_checkers = ['jshint', 'jscs']
